stock_names = {
    'AARVI.NS': 'Aarvi Encon Ltd.',
    'ADROITINFO.NS': 'Adroit Infotech Ltd.',
    'ALLSEC.NS': 'Allsec Technologies Ltd.',
    'ARCHIDPLY.NS': 'Archidply Industries Ltd.',
    'CHOICEIN.NS': 'Choice International Ltd.',
    'FCSSOFT.NS': 'FCS Software Solutions Ltd.',
    'GTECJAINX.NS': 'G Tec Jainx Ltd.',
    'GLOBAL.NS': 'Global Education Ltd.',
    'GVPTECH.NS': 'GVP Technologies Ltd.',
    'ICRA.NS': 'ICRA Ltd.',
    'MITCON.NS': 'Mitcon Consultancy & Engineering Services Ltd.',
    'ONEPOINT.NS': 'One Point Solutions Ltd.',
    'REPRO.NS': 'Repro India Ltd.',
    'RITES.NS': 'RITES Ltd.',
    'SECURCRED.NS': 'Secur Industries Ltd.',
    'SNOWMAN.NS': 'Snowman Logistics Ltd.',
    'SYNGENE.NS': 'Syngene International Ltd.',
    'TCPLPACK.NS': 'TCPL Packaging Ltd.',
    'TEAMLEASE.NS': 'TeamLease Services Ltd.',
    'BHARTIARTL.NS': 'Bharti Airtel Ltd.',
    'RAILTEL.NS': 'Railtel Corporation of India Ltd.',
    'TATACOMM.NS': 'Tata Communications Ltd.',
    'UNIINFO.NS': 'Uniinfo Telecom Services Ltd.',
    'ANANTRAJ.NS': 'Anant Raj Ltd.',
    'APOLLOTYRE.NS': 'Apollo Tyres Ltd.',
    'BAJAJELEC.NS': 'Bajaj Electricals Ltd.',
    'BCONCEPTS.NS': 'B. Concepts Ltd.',
    'BUTTERFLY.NS': 'Butterfly Gandhimathi Appliances Ltd.',
    'CEATLTD.NS': 'CEAT Ltd.',
    'CERA.NS': 'Cera Sanitaryware Ltd.',
    'IFBIND.NS': 'IFB Industries Ltd.',
    'JKTYRE.NS': 'JK Tyre & Industries Ltd.',
    'JTEKTINDIA.NS': 'JTEKT India Ltd.',
    'KDDL.NS': 'KDDL Ltd.',
    'KHAITANLTD.NS': 'Khaitan Ltd.',
    'KOKUYOCMLN.NS': 'Kokuyo Camlin Ltd.',
    'LAOPALA.NS': 'La Opala RG Ltd.',
    'NCC.NS': 'NCC Ltd.',
    'NILKAMAL.NS': 'Nilkamal Ltd.',
    'SMLISUZU.NS': 'SML Isuzu Ltd.',
    'SONAMLTD.NS': 'Sonam Clock Ltd.',
    'TATAMOTORS.NS': 'Tata Motors Ltd.',
    'TITAN.NS': 'Titan Company Ltd.',
    'TBZ.NS': 'Tribhovandas Bhimji Zaveri Ltd.',
    'SANDHAR.NS': 'Sandhar Technologies Ltd.',
    'SILGO.NS': 'Silicon Valley (India) Ltd.',
    'ADFFOODS.NS': 'ADF Foods Ltd.',
    'APEX.NS': 'Apex Frozen Foods Ltd.',
    'BATAINDIA.NS': 'Bata India Ltd.',
    'BHANDARI.NS': 'Bhandari Hosiery Exports Ltd.',
    'BRITANNIA.NS': 'Britannia Industries Ltd.',
    'CANTABIL.NS': 'Cantabil Retail India Ltd.',
    'COLPAL.NS': 'Colgate-Palmolive (India) Ltd.',
    'CUPID.NS': 'Cupid Ltd.',
    'EIFFL.NS': 'Eiffel International Ltd.',
    'GALAXYSURF.NS': 'Galaxy Surfactants Ltd.',
    'GOCOLORS.NS': 'Go Colors Ltd.',
    'GODFRYPHLP.NS': 'Godfrey Phillips India Ltd.',
    'HNDFDS.NS': 'Hindustan Foods Ltd.',
    'HINDUNILVR.NS': 'Hindustan Unilever Ltd.',
    'INDTERRAIN.NS': 'Indo Count Industries Ltd.',
    'ITC.NS': 'ITC Ltd.',
    'JYOTHYLAB.NS': 'Jyothy Labs Ltd.',
    'KKCL.NS': 'Khyati Kesar Commercial Ltd.',
    'KHADIM.NS': 'Khadim India Ltd.',
    'LIBERTSHOE.NS': 'Liberty Shoes Ltd.',
    'LINC.NS': 'Linc Pen & Plastics Ltd.',
    'BECTORFOOD.NS': 'Bector Food Specialities Ltd.',
    'NESTLEIND.NS': 'Nestlé India Ltd.',
    'NORBTEAEXP.NS': 'North Eastern Tea Association Ltd.',
    'PARAGMILK.NS': 'Parag Milk Foods Ltd.',
    'PGIL.NS': 'P.G. Industries Ltd.',
    'DIAMONDYD.NS': 'Diamond Yards Ltd.',
    'SPLIL.NS': 'SPL Industries Ltd.',
    'TASTYBITE.NS': 'Tasty Bite Eatables Ltd.',
    'TATACONSUM.NS': 'Tata Consumer Products Ltd.',
    'TI.NS': 'Titan Industries Ltd.',
    'UNITEDTEA.NS': 'United Tea Ltd.',
    'VADILALIND.NS': 'Vadilal Industries Ltd.',
    'VARDHACRLC.NS': 'Vardhman Acrylics Ltd.',
    'VBL.NS': 'Varun Beverages Ltd.',
    'VIPCLOTHING.NS': 'VIP Clothing Ltd.',
    'WELSPUNLIV.NS': 'Welspun Investments and Commercials Ltd.',
    'ZENITHEXPO.NS': 'Zenith Exports Ltd.',
    'ADVANIHOTR.NS': 'Advani Hotels & Resorts (India) Ltd.',
    'BYKE.NS': 'The Byke Hospitality Ltd.',
    'CHALET.NS': 'Chalet Hotels Ltd.',
    'CINELINE.NS': 'Cinevista Ltd.',
    'CYBERMEDIA.NS': 'Cyber Media (India) Ltd.',
    'DBCORP.NS': 'D B Corp Ltd.',
    'EIHAHOTELS.NS': 'EIH Associated Hotels Ltd.',
    'EIHOTEL.NS': 'EIH Ltd.',
    'GFLLIMITED.NS': 'GFL Ltd.',
    'HLVLTD.NS': 'Hindustan Aeronautics Ltd.',
    'INDHOTEL.NS': 'Indian Hotels Company Ltd.',
    'LEMONTREE.NS': 'Lemon Tree Hotels Ltd.',
    'MHRIL.NS': 'Mahindra Holidays & Resorts India Ltd.',
    'MPSLTD.NS': 'MPS Ltd.',
    'NDLVENTURE.NS': 'NDL Ventures Ltd.',
    'ORIENTHOT.NS': 'Oriental Hotels Ltd.',
    'PFOCUS.NS': 'P.F. International Ltd.',
    'ROHLTD.NS': 'Rohit Ferro-Tech Ltd.',
    'SCHAND.NS': 'S. Chand and Company Ltd.',
    'SANDESH.NS': 'Sandesh Ltd.',
    'TAJGVK.NS': 'Taj GVK Hotels & Resorts Ltd.',
    'TGBHOTELS.NS': 'TGB Banquets & Hotels Ltd.',
    'TIPSINDLTD.NS': 'Tips Industries Ltd.',
    'WESTLIFE.NS': 'Westlife Development Ltd.',
    'WONDERLA.NS': 'Wonderla Holidays Ltd.',
    'ADANIENT.NS': 'Adani Enterprises Ltd.',
    'GMDCLTD.NS': 'Gujarat Mineral Development Corporation Ltd.',
    'JAYBARMARU.NS': 'Jaybharat Textile & Real Estate Ltd.',
    'KOTHARIPRO.NS': 'Kothari Products Ltd.',
    'SAKUMA.NS': 'Sakuma Exports Ltd.',
    'SCHNEIDER.NS': 'Schneider Electric Infrastructure Ltd.',
    'HAVISHA.NS': 'Havisha Ltd.',
    'SURANAT&P.NS': 'Suranat & Parikh Ltd.',
    'APARINDS.NS': 'Apar Industries Ltd.',
    'BEL.NS': 'Bharat Electronics Ltd.',
    'CENTUM.NS': 'Centum Electronics Ltd.',
    'CONTROLPR.NS': 'Control Print Ltd.',
    'DLINKINDIA.NS': 'D-Link (India) Ltd.',
    'DENORA.NS': 'De Nora India Ltd.',
    'DIXON.NS': 'Dixon Technologies (India) Ltd.',
    'HPL.NS': 'HPL Electric & Power Ltd.',
    'NELCO.NS': 'Nelco Ltd.',
    'SURANASOL.NS': 'Suranas Solutions Ltd.',
    'UNIVCABLES.NS': 'Univ Cables Ltd.',
    'CHENNPETRO.NS': 'Chennai Petroleum Corporation Ltd.',
    'COALINDIA.NS': 'Coal India Ltd.',
    'GULFPETRO.NS': 'Gulf Oil Lubricants India Ltd.',
    'HINDOILEXP.NS': 'Hindustan Oil Exploration Company Ltd.',
    'MRPL.NS': 'Mangalore Refinery and Petrochemicals Ltd.',
    'OIL.NS': 'Oil India Ltd.',
    'SELAN.NS': 'Selan Exploration Technology Ltd.',
    'AJMERA.NS': 'Ajmera Realty & Infra India Ltd.',
    'APOLLOPIPE.NS': 'Apollo Pipes Ltd.',
    'AVONMORE.NS': 'Avonmore Capital & Management Services Ltd.',
    'BAJAJHLDNG.NS': 'Bajaj Holdings & Investment Ltd.',
    'CMSINFO.NS': 'CMS Info Systems Ltd.',
    'CSBBANK.NS': 'CSB Bank Ltd.',
    'DELPHIFX.NS': 'Delphi Technologies PLC',
    'DHANBANK.NS': 'Dhanlaxmi Bank Ltd.',
    'DLF.NS': 'DLF Ltd.',
    'ELDEHSG.NS': 'Elder Healthcare Ltd.',
    'GANESHHOUC.NS': 'Ganesh Housing Corporation Ltd.',
    'GICRE.NS': 'General Insurance Corporation of India Ltd.',
    'GICHSGFIN.NS': 'GIC Housing Finance Ltd.',
    'ICDSLTD.NS': 'ICDS Ltd.',
    'ICICIGI.NS': 'ICICI Lombard General Insurance Co. Ltd.',
    'IDFCFIRSTB.NS': 'IDFC First Bank Ltd.',
    'INDOSTAR.NS': 'Indostar Capital Finance Ltd.',
    'IITL.NS': 'IITL Ltd.',
    'JPOLYINVST.NS': 'J P Polyinvest Ltd.',
    'KTKBANK.NS': 'Ktk Bank Ltd.',
    'KHANDSE.NS': 'Khandse Limited',
    'KOLTEPATIL.NS': 'Kolte-Patil Developers Ltd.',
    'LFIC.NS': 'L.F. Industries Ltd.',
    'LICI.NS': 'Life Insurance Corporation of India Ltd.',
    'LODHA.NS': 'Lodha Developers Ltd.',
    'MANINFRA.NS': 'Man Infraconstruction Ltd.',
    'MARATHON.NS': 'Marathon Nextgen Realty Ltd.',
    'MUTHOOTCAP.NS': 'Muthoot Capital Services Ltd.',
    'NSIL.NS': 'NSIL Ltd.',
    'PHOENIXLTD.NS': 'Phoenix Mills Ltd.',
    'PILANIINVS.NS': 'Pilani Investment and Industries Corporation Ltd.',
    'PEL.NS': 'Power Electronics Ltd.',
    'PROZONER.NS': 'Prozone Intu Properties Ltd.',
    'PRUDENT.NS': 'Prudent Corporate Advisory Services Ltd.',
    'PFS.NS': 'PFS Ltd.',
    'RELIGARE.NS': 'Religare Enterprises Ltd.',
    'SANGHVIMOV.NS': 'Sanghvi Movers Ltd.',
    'SILINV.NS': 'Silicon Valley (India) Ltd.',
    'STARTECK.NS': 'Starteck Finance Ltd.',
    'TIMESGTY.NS': 'Times Guaranty Ltd.',
    'WEALTH.NS': 'Wealth Finance Ltd.',
    'RBLBANK.NS': 'RBL Bank Ltd.',
    'FORTIS.NS': 'Fortis Healthcare Ltd.',
    'MEDANTA.NS': 'Medanta Ltd.',
    'INDRAMEDCO.NS': 'Indraprastha Medical Corporation Ltd.',
    'LOTUSEYE.NS': 'Lotus Eye Hospital & Institute Ltd.',
    'MAXHEALTH.NS': 'Max Healthcare Institute Ltd.',
    'NH.NS': 'Narayana Hrudayalaya Ltd.',
    'RAINBOW.NS': 'Rainbow Children’s Medicare Ltd.',
    'SHALBY.NS': 'Shalby Ltd.',
    'ALEMBICLTD.NS': 'Alembic Ltd.',
    'APLLTD.NS': 'APL Apollo Tubes Ltd.',
    'ALKEM.NS': 'Alkem Laboratories Ltd.',
    'ASTRAZEN.NS': 'AstraZeneca Pharma India Ltd.',
    'BAFNAPH.NS': 'Bafna Pharmaceuticals Ltd.',
    'CIPLA.NS': 'Cipla Ltd.',
    'DRREDDY.NS': 'Dr. Reddy\'s Laboratories Ltd.',
    'GRANULES.NS': 'Granules India Ltd.',
    'INDSWFTLAB.NS': 'Ind-Swift Laboratories Ltd.',
    'JAGSNPHARM.NS': 'Jagsn Pharmaceuticals Ltd.',
    'KILITCH.NS': 'Kilitch Drugs (India) Ltd.',
    'MEDICO.NS': 'Medico Remedies Ltd.',
    'NATCOPHARM.NS': 'Natco Pharma Ltd.',
    'NEULANDLAB.NS': 'Neuland Laboratories Ltd.',
    'NGLFINE.NS': 'NGL Fine-Chem Ltd.',
    'ORCHPHARMA.NS': 'Orchid Pharma Ltd.',
    'POLYMED.NS': 'Polymedicure Ltd.',
    'RPGLIFE.NS': 'RPG Life Sciences Ltd.',
    'SUNPHARMA.NS': 'Sun Pharmaceutical Industries Ltd.',
    'TORNTPHARM.NS': 'Torrent Pharmaceuticals Ltd.',
    'VENUSREM.NS': 'Venus Remedies Ltd.',
    'WINDLAS.NS': 'Windlas Biotech Ltd.',
    'ZYDUSLIFE.NS': 'Zydus Lifesciences Ltd.',
    'AHLUCONT.NS': 'Ahlcon Consultants Ltd.',
    'ARSSINFRA.NS': 'ARSS Infrastructure Projects Ltd.',
    'ASHOKA.NS': 'Ashoka Buildcon Ltd.',
    'BLKASHYAP.NS': 'BL Kashyap & Sons Ltd.',
    'DEEPINDS.NS': 'Deep Industries Ltd.',
    'ENGINERSIN.NS': 'Engineers India Ltd.',
    'GRINFRA.NS': 'GR Infrastructure Ltd.',
    'GMRP&UI.NS': 'GMR Power & Urban Infra Ltd.',
    'HECPROJECT.NS': 'HEC Projects Ltd.',
    'IRB.NS': 'IRB Infrastructure Developers Ltd.',
    'ISGEC.NS': 'ISGEC Heavy Engineering Ltd.',
    'ITDCEM.NS': 'ITD Cementation India Ltd.',
    'JINDRILL.NS': 'Jindal Drilling & Industries Ltd.',
    'JSWINFRA.NS': 'JSW Infrastructure Ltd.',
    'KNRCON.NS': 'KNR Constructions Ltd.',
    'LTTS.NS': 'L&T Technology Services Ltd.',
    'LT.NS': 'Larsen & Toubro Ltd.',
    'MODISONLTD.NS': 'Modison Metals Ltd.',
    'MOLDTECH.NS': 'Mold-Tek Packaging Ltd.',
    'PATELENG.NS': 'Patel Engineering Ltd.',
    'POWERMECH.NS': 'Power Mech Projects Ltd.',
    'RAMKY.NS': 'Ramky Infrastructure Ltd.',
    'RIIL.NS': 'Rites Ltd.',
    'RKEC.NS': 'RKEC Projects Ltd.',
    'RPPINFRA.NS': 'RPP Infra Projects Ltd.',
    'SHRADHA.NS': 'Shradha Infrastructure Ltd.',
    'TARMAT.NS': 'Tarmat Ltd.',
    'UNIVASTU.NS': 'Univastu India Ltd.',
    'WABAG.NS': 'VA Tech Wabag Ltd.',
    'VASCONEQ.NS': 'Vascon Engineers Ltd.',
    'WELENT.NS': 'Welspun Enterprises Ltd.',
    'AIROLAM.NS': 'Airolam Limited',
    'AMBUJACEM.NS': 'Ambuja Cements Limited',
    'ASHAPURMIN.NS': 'Ashapura Minechem Limited',
    'BVCL.NS': 'Barak Valley Cements Limited',
    'BEDMUTHA.NS': 'Bedmutha Industries Limited',
    'BIGBLOC.NS': 'Bigbloc Construction Limited',
    'BIRLACORPN.NS': 'Birla Corporation Limited',
    'CUBEXTUB.NS': 'CUBEX Tubings Limited',
    'ELECTCAST.NS': 'Electrosteel Castings Limited',
    'GANDHITUBE.NS': 'Gandhi Special Tubes Limited',
    'GATEWAY.NS': 'Gateway Distriparks Limited',
    'GEEKAYWIRE.NS': 'Geekay Wires Limited',
    'GRAVITA.NS': 'Gravita India Limited',
    'GREENPANEL.NS': 'Greenpanel Industries Limited',
    'HINDALCO.NS': 'Hindalco Industries Limited',
    'HINDCON.NS': 'Hindustan Construction Company Limited',
    'HISARMETAL.NS': 'Hisar Metal Industries Limited',
    'HPAL.NS': 'Himachal Pradesh Agro Industries Corporation Limited',
    'INCREDIBLE.NS': 'Incredible Industries Limited',
    'ISMTLTD.NS': 'ISMT Limited',
    'JINDALSAW.NS': 'Jindal SAW Limited',
    'JSL.NS': 'Jindal Stainless Limited',
    'KAMDHENU.NS': 'Kamdhenu Limited',
    'KIRLOSIND.NS': 'Kirloskar Industries Limited',
    'MAHSEAMLES.NS': 'Maharashtra Seamless Limited',
    'MANAKALUCO.NS': 'Manaksia Aluminium Company Limited',
    'MMP.NS': 'MMP Industries Limited',
    'NCLIND.NS': 'NCL Industries Limited',
    'NELCAST.NS': 'Nelcast Limited',
    'ORIENTCER.NS': 'Orient Ceramics and Industries Limited',
    'PENIND.NS': 'Pennar Industries Limited',
    'PRAKASH.NS': 'Prakash Industries Limited',
    'PREMIERPOL.NS': 'Premier Polyfilm Limited',
    'RATNAMANI.NS': 'Ratnamani Metals & Tubes Limited',
    'RESPONIND.NS': 'Responsive Industries Limited',
    'SAGARDEEP.NS': 'Sagardeep Alloys Limited',
    'SALSTEEL.NS': 'S.A.L. Steel Limited',
    'SARDAEN.NS': 'Sarda Energy & Minerals Limited',
    'SMLT.NS': 'Steelco Gujarat Limited',
    'SHREDIGCEM.NS': 'Shree Digvijay Cement Co. Limited',
    'STEELCAS.NS': 'Steelcast Limited',
    'STYLAMIND.NS': 'Stylam Industries Limited',
    'SURYAROSNI.NS': 'Surya Roshni Limited',
    'SGIL.NS': 'Shree Ganesh Jewellery House (I) Limited',
    '20MICRONS.NS': '20 Microns Limited',
    'AGI.NS': 'AGI Greenpac Limited',
    'AMBICAAGAR.NS': 'Ambica Agarbathies Aroma & Industries Limited',
    'ANDHRAPAP.NS': 'Andhra Paper Limited',
    'ARVIND.NS': 'Arvind Limited',
    'ASIANPAINT.NS': 'Asian Paints Limited',
    'AVANTIFEED.NS': 'Avanti Feeds Limited',
    'BANSWRAS.NS': 'Banswara Syntex Limited',
    'BAYERCROP.NS': 'Bayer CropScience Limited',
    'BEARDSELL.NS': 'Beardsell Limited',
    'CENTURYTEX.NS': 'Century Textiles and Industries Limited',
    'CLSEL.NS': 'CL Educate Limited',
    'DCMSRIND.NS': 'DCM Shriram Industries Limited',
    'DHAMPURSUG.NS': 'Dhampur Sugar Mills Limited',
    'DHANUKA.NS': 'Dhanuka Agritech Limited',
    'FAZE3Q.NS': 'Faze Three Limited',
    'FCL.NS': 'Future Consumer Limited',
    'FOSECOIND.NS': 'Foseco India Limited',
    'GHCL.NS': 'GHCL Limited',
    'GSFC.NS': 'Gujarat State Fertilizers & Chemicals Limited',
    'HSCL.NS': 'Hindustan Salts Limited',
    'HUHTAMAKI.NS': 'Huhtamaki India Limited',
    'INDOAMIN.NS': 'Indo Amines Limited',
    'IVP.NS': 'IVP Limited',
    'JUBLINDS.NS': 'Jubilant Industries Limited',
    'KANSAINER.NS': 'Kansai Nerolac Paints Limited',
    'KSCL.NS': 'Kaveri Seed Company Limited',
    'KOTARISUG.NS': 'Kothari Sugars & Chemicals Limited',
    'KRITINUT.NS': 'Kriti Nutrients Limited',
    'LINDEINDIA.NS': 'Linde India Limited',
    'LTFOODS.NS': 'LT Foods Limited',
    'MAGADSUGAR.NS': 'Magadh Sugar & Energy Limited',
    'MAYURUNIQ.NS': 'Mayur Uniquoters Limited',
    'MEGASTAR.NS': 'Megastar Foods Limited',
    'NRAIL.NS': 'N R Agarwal Industries Limited',
    'PAR.NS': 'Pioneer Agro Extracts Limited',
    'PIDILITIND.NS': 'Pidilite Industries Limited',
    'PLASTIBLEN.NS': 'Plastiblends India Limited',
    'RCF.NS': 'Rashtriya Chemicals and Fertilizers Limited',
    'SHK.NS': 'S H Kelkar and Company Limited',
    'SANGINITA.NS': 'Sanginita Chemicals Limited',
    'SESHAPAPER.NS': 'Seshasayee Paper and Boards Limited',
    'SHREERAMA.NS': 'Shree Rama Newsprint Limited',
    'SHREYANIND.NS': 'Shreyans Industries Limited',
    'SIGIND.NS': 'Signet Industries Limited',
    'SIYSIL.NS': 'Siyaram Silk Mills Limited',
    'SKMEGGPROD.NS': 'SKM Egg Products Export (India) Limited',
    'SOLARINDS.NS': 'Solar Industries India Limited',
    'SRHHYPOLTD.NS': 'Sree Rayalaseema Hi-Strength Hypo Limited',
    'STARPAPER.NS': 'Star Paper Mills Limited',
    'SULA.NS': 'Sula Vineyards Limited',
    'SUMICHEM.NS': 'Sumitomo Chemical India Limited',
    'SURYALAXMI.NS': 'Suryalakshmi Cotton Mills Limited',
    'TATACHEM.NS': 'Tata Chemicals Limited',
    'TIMETECHNO.NS': 'Time Technoplast Limited',
    'TRIVENI.NS': 'Triveni Engineering & Industries Limited',
    'UGARSUGAR.NS': 'The Ugar Sugar Works Limited',
    'UPL.NS': 'UPL Limited',
    'UTTAMSUGAR.NS': 'Uttam Sugar Mills Limited',
    'VINATIORGA.NS': 'Vinati Organics Limited',
    'VISHNU.NS': 'Vishnu Chemicals Limited',
    'WORTH.NS': 'Worth Peripherals Limited',
    'XPROINDIA.NS': 'Xpro India Limited',
    'KIRLOSBROS.NS': 'Kirloskar Brothers Limited',
    'EIMCOELECO.NS': 'Eimco Elecon (India) Limited',
    'MACPOWER.NS': 'Macpower CNC Machines Limited',
    'GRPLTD.NS': 'GRP Limited',
    'RANEHOLDIN.NS': 'Rane Holdings Limited',
    'AUTOIND.NS': 'Automotive Axles Limited',
    'HONDAPOWER.NS': 'Honda Power Products Limited',
    'PRICOLLTD.NS': 'Pricol Limited',
    'SUVENPHAR.NS': 'Suven Pharmaceuticals Limited',
    'SUNDRMFAST.NS': 'Sundram Fasteners Limited',
    'FIEMIND.NS': 'FIEM Industries Limited',
    'IGARASHI.NS': 'Igarashi Motors India Limited',
    'KECL.NS': 'Kirloskar Electric Company Limited',
    'SCHAEFFLER.NS': 'Schaeffler India Limited',
    'LUMAXIND.NS': 'Lumax Industries Limited',
    'ARE&M.NS': 'AR Engineering and Manufacturing Limited',
    'PARACABLES.NS': 'Paramount Communications Limited',
    'ARCHIDPLY.NS': 'Archidply Industries Limited',
    'MAZDA.NS': 'Mazda Limited',
    'WSTCSTPAPR.NS': 'West Coast Paper Mills Limited',
    'VOLTAMP.NS': 'Voltamp Transformers Limited',
    'USHAMART.NS': 'Usha Martin Limited',
    'URAVI.NS': 'Uravi T and Wedge Lamps Limited',
    'UNIPARTS.NS': 'Uniparts India Limited',
    'TRIL.NS': 'Transformers and Rectifiers (India) Limited',
    'TITAGARH.NS': 'Titagarh Wagons Limited',
    'THERMAX.NS': 'Thermax Limited',
    'TDPOWERSYS.NS': 'TD Power Systems Limited',
    'TALBROAUTO.NS': 'Talbros Automotive Components Limited',
    'SUPREMEIND.NS': 'Supreme Industries Limited',
    'SUBROS.NS': 'Subros Limited',
    'STERTOOLS.NS': 'Sterling Tools Limited',
    'SOMICONVEY.NS': 'Somi Conveyor Beltings Limited',
    'SKIPPER.NS': 'Skipper Limited',
    'SJS.NS': 'SJS Enterprises Limited',
    'SIEMENS.NS': 'Siemens Limited',
    'SHRIPISTON.NS': 'Shriram Pistons and Rings Limited',
    'SHANTIGEAR.NS': 'Shanthi Gears Limited',
    'SANSERA.NS': 'Sansera Engineering Limited',
    'MOTHERSON.NS': 'Motherson Sumi Systems Limited',
    'SALZERELEC.NS': 'Salzer Electronics Limited',
    'ROLEXRINGS.NS': 'Rolex Rings Limited',
    'RICOAUTO.NS': 'Rico Auto Industries Limited',
    'REMSONSIND.NS': 'Remsons Industries Limited',
    'RBL.NS': 'RBL Bank Limited',
    'RML.NS': 'Rane (Madras) Limited',
    'PTCIL.NS': 'PTC India Limited',
    'PRINCEPIPE.NS': 'Prince Pipes and Fittings Limited',
    'PPL.NS': 'Peninsula Land Limited',
    'POKARNA.NS': 'Pokarna Limited',
    'PIXTRANS.NS': 'Pix Transmissions Limited',
    'PITTIENG.NS': 'Pitti Engineering Limited',
    'PILITA.NS': 'PIL ITALICA Lifestyle Limited',
    'NRBBEARING.NS': 'NRB Bearings Limited',
    'NESCO.NS': 'NESCO Limited',
    'NDRAUTO.NS': 'NDR Auto Components Limited',
    'MUNJALSHOW.NS': 'Munjal Showa Limited',
    'MMFL.NS': 'Mishra Dhatu Nigam Limited',
    'MENONBE.NS': 'Menon Bearings Limited',
    'MAZDOCK.NS': 'Mazagon Dock Shipbuilders Limited',
    'KRITIKA.NS': 'Kriti Industries (India) Limited',
    'KEI.NS': 'KEI Industries Limited',
    'JAYNECOIND.NS': 'Jay Neeco Industries Limited',
    'JASH.NS': 'Jash Engineering Limited',
    'JAMNAAUTO.NS': 'Jamna Auto Industries Limited',
    'INTLCONV.NS': 'International Conveyors Limited',
    'INDNIPPON.NS': 'India Nippon Electricals Limited',
    'ICEMAKE.NS': 'ICEMAK Refrigeration Limited',
    'HINDWAREAP.NS': 'Hindware Home Innovation Limited',
    'HINDCOMPOS.NS': 'Hindustan Composites Limited',
    'HITECHGEAR.NS': 'Hi-Tech Gears Limited',
    'HERCULES.NS': 'Hercules Hoists Limited',
    'GMMPFAUDLR.NS': 'GMM Pfaudler Limited',
    'GRSE.NS': 'Garden Reach Shipbuilders & Engineers Limited',
    'GABRIEL.NS': 'Gabriel India Limited',
    'FINPIPE.NS': 'Finolex Industries Limited',
    'FINCABLES.NS': 'Finolex Cables Limited',
    'FMGOETZE.NS': 'Federal-Mogul Goetze (India) Limited',
    'ESABINDIA.NS': 'Esab India Limited',
    'ELGIEQUIP.NS': 'Elgi Equipments Limited',
    'ELECON.NS': 'Elecon Engineering Company Limited',
    'DYNAMATECH.NS': 'Dynamatic Technologies Limited',
    'DPWIRES.NS': 'D P Wires Limited',
    'CUMMINSIND.NS': 'Cummins India Limited',
    'CRAFTSMAN.NS': 'Craftsman Automation Limited',
    'CORDSCABLE.NS': 'Cords Cable Industries Limited',
    'CENTEXT.NS': 'Century Extrusions Limited',
    'BHARATWIRE.NS': 'Bharat Wire Ropes Limited',
    'BBL.NS': 'Bharat Bijlee Limited',
    'BALMLAWRIE.NS': 'Balmer Lawrie & Company Limited',
    'AUTOAXLES.NS': 'Automotive Axles Limited',
    'AMBER.NS': 'Amber Enterprises India Limited',
    'AIAENG.NS': 'AIA Engineering Limited',
    'AHLADA.NS': 'Ahlada Engineers Limited',
    'ADORWELD.NS': 'Ador Welding Limited',
    'ACE.NS': 'Action Construction Equipment Limited',
    'ABB.NS': 'ABB India Limited',
    'SREEL.NS': 'Sreeleathers Limited',
    'DMART.NS': 'Avenue Supermarts Limited',
    'MEDPLUS.NS': 'MedPlus Health Services Limited',
    'SHOPERSTOP.NS': 'Shoppers Stop Limited',
    'ARVINDFASN.NS': 'Arvind Fashions Limited',
    'SHANKARA.NS': 'Shankara Building Products Limited',
    'MANYAVAR.NS': 'Vedant Fashions Limited',
    'KALYANKJIL.NS': 'Kalyan Jewellers India Limited',
    'ARCHIES.NS': 'Archies Limited',
    'DPABHUSHAN.NS': 'D. P. Abhushan Limited',
    'MSTCLTD.NS': 'MSTC Limited',
    'TRENT.NS': 'Trent Limited',
    'COMPUSOFT.NS': 'Compucom Software Limited',
    'E2E.NS': 'E2E Networks Limited',
    'IRIS.NS': 'IRIS Business Services Limited',
    'HOVS.NS': 'HOV Services Limited',
    'AAATECH.NS': 'Aaa Technologies Limited',
    'SILVERTUC.NS': 'Silver Touch Technologies Limited',
    'ZENTEC.NS': 'Zen Technologies Limited',
    'CARTRADE.NS': 'CarTrade Tech Limited',
    'ZENSARTECH.NS': 'Zensar Technologies Limited',
    'HCLTECH.NS': 'HCL Technologies Limited',
    'NUCLEUS.NS': 'Nucleus Software Exports Limited',
    'LOKESHMACH.NS': 'Lokesh Machines Limited',
    'CIGNITITEC.NS': 'Cigniti Technologies Limited',
    'TATAELXSI.NS': 'Tata Elxsi Limited',
    'MPHASIS.NS': 'Mphasis Limited',
    'AIRAN.NS': 'Airan Limited',
    'ACCELYA.NS': 'Accelya Solutions India Limited',
    'VIRINCHI.NS': 'Virinchi Limited',
    'TERASOFT.NS': 'Tera Software Limited',
    'BLS.NS': 'BLS International Services Limited',
    'AFFLE.NS': 'Affle (India) Limited',
    'DATAMATICS.NS': 'Datamatics Global Services Limited',
    'STLTECH.NS': 'Sterlite Technologies Limited',
    'CRISIL.NS': 'CRISIL Limited',
    'SAKSOFT.NS': 'Saksoft Limited',
    'MINDTECK.NS': 'Mindteck (India) Limited',
    'IZMO.NS': 'izmo Limited',
    'ALLCARGO.NS': 'Allcargo Logistics Limited',
    'NAVKARCORP.NS': 'Navkar Corporation Limited',
    'CONCOR.NS': 'Container Corporation of India Limited',
    'GESHIP.NS': 'The Great Eastern Shipping Company Limited',
    'ASPINWALL.NS': 'Aspinwall and Company Limited',
    'GPPL.NS': 'Gujarat Pipavav Port Limited',
    'SCI.NS': 'Shipping Corporation of India Limited'
}
